USB_VID = 0x2341
USB_PID = 0x8052
USB_PRODUCT = "OpenRB-150"
USB_MANUFACTURER = "ROBOTIS"

CHIP_VARIANT = SAMD21G18A
CHIP_FAMILY = samd21

# Restore the USB flash drive and internal file system
SPI_FLASH_FILESYSTEM = 0
INTERNAL_FLASH_FILESYSTEM = 1
CIRCUITPY_USB_MSC = 1

# ENABLE NATIVE LONG INTEGER MATH TO ELIMINATE OVERFLOW CODES
LONGINT_IMPL = MPZ

# Maintain aggressive core feature stripping to fit in flash
CIRCUITPY_DISPLAYIO = 0
CIRCUITPY_TERMINALIO = 0
CIRCUITPY_VECTORIO = 0
CIRCUITPY_AUDIOIO = 0
CIRCUITPY_AUDIOPCHM = 0
CIRCUITPY_AUDIOMP3 = 0
CIRCUITPY_TOUCHIO = 0
CIRCUITPY_NEOPIXEL_WRITE = 0
CIRCUITPY_RGBMATRIX = 0
CIRCUITPY_SHARPMEM = 0
CIRCUITPY_PULSEIO = 0
CIRCUITPY_PEW = 0
CIRCUITPY_KEYPAD = 0
CIRCUITPY_MATH = 1
CIRCUITPY_BITMAPTOOLS = 0
CIRCUITPY_RE = 0

# Maintain required communication frameworks
CIRCUITPY_BITBANGIO = 0
CIRCUITPY_BUSDEVICE = 1
CIRCUITPY_DIGITALIO = 1
CIRCUITPY_ANALOGIO = 1

FROZEN_MPY_DIRS += $(TOP)/ports/atmel-samd/frozen


